### ISSUE TITLE
Remove last data row here before of add a new register

### ISSUE THREAD

**Issue by iurynogueira** [espoo-dev/the_reef#149]
https://github.com/iurynogueira/myreef/blob/00056517ae8857e2687f341eee66f8eaad06e95e/back/src/infra/repository/database/IndicatorHistoricRepositoryDatabase.ts#L8

**Comment by isaqueveras** [comment]
How will the graph look?

**Comment by iurynogueira** [comment]
> How will the graph look?

Chart not change with this, this will avoid having a lot of unnecessary data in the table.
