### ISSUE TITLE
Improve Fish entity

### ISSUE THREAD

**Issue by iurynogueira** [espoo-dev/the_reef#60]
A fish should has:
  - scientific and common name
  - should has image
  - description
  - reef safe (true or false) true when the fish is an animals of the reef community
  - list of others fishs that should not be in same reef

  - difficulty to maintain being them:
    - To newbies
    - Need more careful
    - Only experients aquarists

**Comment by mizek1** [comment]
Can I work on this one? =D

**Comment by iurynogueira** [comment]
> Can I work on this one? =D

Yep!
